version: "3"
services:
  server:
    build:
      context: ./server/
    command: npm start
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file: ./server/.env

  client:
    build:
      context: ./client
    command: npm run dev
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
